// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Oct 17 16:17:33 2019

BRAM BRAM_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.wr_en(wr_en_sig) ,	// input  wr_en_sig
	.waddr(waddr_sig) ,	// input [MEMWIDTH-1:0] waddr_sig
	.raddr(raddr_sig) ,	// input [MEMWIDTH-1:0] raddr_sig
	.data_in(data_in_sig) ,	// input [DATAWIDTH-1:0] data_in_sig
	.data_out(data_out_sig) 	// output [DATAWIDTH-1:0] data_out_sig
);

defparam BRAM_inst.MEMWIDTH = 10;
defparam BRAM_inst.DATAWIDTH = 32;
